name: Check links

on:
  pull_request:

jobs:
  markdown-link-check:
    name: Check links using markdwon-link-check
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check links on new changes
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: "mlc_config.json"
          check-modified-files-only: "yes"
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
